name: CI for Integration Service WebSocket SystemHandle

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - '**'

jobs:
  websocket-sh_CI:
    runs-on: ubuntu-20.04
    container: ubuntu:focal

    steps:
      - uses: actions/checkout@v2
        with:
          path: src/websocket-sh

      - name: Download required dependencies
        run: |
          apt update
          DEBIAN_FRONTEND=noninteractive apt install -y cmake gcc g++ git libboost-dev libboost-program-options-dev
          apt install -y libyaml-cpp-dev libssl-dev libwebsocketpp-dev

      - name: Install colcon
        run: |
          apt install -y python3-pip
          pip3 install -U colcon-common-extensions

      - name: Download the Integration Service Core
        run: |
          git clone -b feature/request_subscription_pools --recursive https://github.com/eProsima/soss src/is-core

      - name: Build
        run: |
          colcon build --packages-up-to is-websocket-test --cmake-args -DBUILD_TESTING=ON --event-handlers console_direct+

      - name: Test
        run: |
          . install/local_setup.sh && colcon test --packages-up-to is-websocket-test --event-handlers console_direct+
          colcon test-result
